spring:
  # Cache properties for redis in cluster
  cache:
    type: redis
    redis:
      time-to-live: 3600000 # 4 hours in milis
      cache-null-values: false
  redis:
    lettuce.pool.min-idle: 4
    lettuce.pool.max-active: 20
    lettuce.pool.max-wait: 5000
    password: ${REDIS_PASSWORD}
    cluster:
      nodes:
        - redis.redis.svc.cluster.local:6379

server:
  connection-timeout: 60000
  session.timeout: 60000
  port: 8080
